### ISSUE TITLE
Memory usage with QDOAS 3.6

### ISSUE THREAD

**Issue by jvangent** [UVVIS-BIRA-IASB/qdoas#1]
It is observed that ```QDOAS v3.6``` is significantly more memory demanding than previous versions.

initial investigation points to the static allocation of array variables related to the GEMS satellite sensor.

Preliminary solutions could consist of working with the re-binned GEMS products (a nett smaller detector size dimensions).

A more substantial solution would require the dynamic allocation of those variables, such that the memory is not allocated when GEMS is not used.

**Comment by tdanckaert** [comment]
This has been improved in qdoas 3.6.3 (also because a memory leak was found and fixed...).
