### ISSUE TITLE
Can this software be used for methane gas concentration inversion？

### ISSUE THREAD

**Issue by CGrookie** [UVVIS-BIRA-IASB/qdoas#2]
Hello, I would like to try using this software for methane gas concentration inversion experiments. I am not sure if QDOAS can theoretically complete this task?

**Comment by tdanckaert** [comment]
Hi, there is no restriction on the spectral range or input cross sections, so QDOAS can be used in the infrared bands where methane is absorbing.  However, I don't know if regular DOAS analysis as described in the QDOAS manual is suitable for methane retrieval.  I have no experience with methane retrievals, but you could look at e.g. https://acp.copernicus.org/articles/6/2727/2006/acp-6-2727-2006.html where a "weighting function modified" DOAS approach is used.  I think it should be possible to include such weighting functions (generated using a RT model) as "cross sections" in QDOAS as well, but don't know if that is the most practical approach.

Note that the official channel for these kind of questions is at the ESA Atmospheric Toolbox forum:

https://forum.atmospherictoolbox.org/c/qdoas/

so if you would like to continue the discussion, I invite you to post there.
