### ISSUE TITLE
cannot read GEMS L1C file (V1.2.4)

### ISSUE THREAD

**Issue by lastproxy** [UVVIS-BIRA-IASB/qdoas#5]
For Qdoas v3.6.3, when browsing the GEMS spectra, the error message shows `Fatal (GEMS_Set) cannot read netCDF variable 'sun_zenith_angle'`

**Comment by lastproxy** [comment]
Such an issue was not observed in Qdoas v3.6.0. However, the memory leak issue of v3.6.0 made it impossible to work properly.

**Comment by tdanckaert** [comment]
Hi, I can't reproduce the problem with my version of QDOAS 3.6.3 (on linux) and GEMS 1.4.2 input data.  Which operating system are you using?  Could you share an example input file where the problem occurs?

**Comment by lastproxy** [comment]
Hi, thanks for your reply. I am using Ubuntu 20.04.6 LTS system, Linux version 5.15.0-91-generic. Here is the google drive link of one example gems l1c file, https://drive.google.com/file/d/1bZFD0IGNjr6lAp4bXikcxqxc92xDSNss/view?usp=sharing

**Comment by lastproxy** [comment]
Similar issue happens for the latest Qdoas v3.6.8 also. And here is the error message:
![Xnip2024-09-10_15-11-22](https://github.com/user-attachments/assets/51404f77-c52e-4b9e-b996-23a19627d41c)

**Comment by tdanckaert** [comment]
The order of dimensions in your example file is different from what QDOAS expects (and from the files we have here): when inspecting the file with `ncdump -h`, I see that `sun_zenith_angle` (as well as other variables) has dimensions `(dim_image_y, dim_image_x)`, whereas the dimension order in the files we have, is `(dim_image_x, dim_image_y)`.

I also notice that the size of the dimensions in your example file is different from `number_of_columns` / `number_of_lines` attribute values.  Is this an original GEMS L1 file, or has it been modified?

**Comment by lastproxy** [comment]
Thanks for investigating that. I download the data from the GEMS FTP server by NIER Korea. It is an original file by the processor version V1.2.4. As for the dimension differences, it may be caused by the fact that the shared example is the 4 * 4 binning version. The FTP server gives L1c file with three types, namely, original resolution, 2 *2bin, and 4 *4 bin.

**Comment by tdanckaert** [comment]
Yes, the binning factor would explain the difference.  I will try to investigate what is going on, but don't have access to download 
new GEMS L1C data at the moment.

Did you try the same file in QDOAS 3.6.0, or was that a different flie?  Because the problem of dimension order should have been the same with that version of QDOAS.

**Comment by lastproxy** [comment]
Yes, I was trying the same file in Qdoas 3.6.0 before. It can browse the spectra and even fit successfully for some records. Due to the memory leak issue, I then updated the software to 3.6.3 and found this spectra read issue.

**Comment by tdanckaert** [comment]
Hi, I've found the cause of the bug.

* At BIRA, we work with modified GEMS files where dimensions are reordered for better reading performance (reading spectra is much faster when the spectral dimension (dim_image_band) comes last, so we use a script to flip the order of dimensions in all GEMS NetCDF files).  Standard GEMS L1C data has dim_image_band as the first dimension.  QDOAS has a mode to work with original GEMS files, too, but as you discovered, this mode has bugs when reading variables without dim_image_band dimension, such as `sun_zenith_angle`.  I'll fix it and publish a new version of QDOAS soon.

* QDOAS 3.6.0 had the same bug, but did not report all NetCDF reading errors (3.6.3 was the first version to properly handle all NetCDF reading errors...).  So reading `sun_zenith_angle` and similar geometric variables silently failed, but spectra were read correctly and could be processed.

**Comment by lastproxy** [comment]
Thanks for your explanation! I am looking forward to the next version of QDOAS, which will eventually solve this issue.

**Comment by tdanckaert** [comment]
Hi, qdoas 3.6.10 is now available from conda.  Please let me know if it works as expected!

**Comment by lastproxy** [comment]
Hi, thanks for solving this issue. I just updated to qdoas 3.6.10 and found it works perfectly now.
