### ISSUE TITLE
About QDOAS version 3.6.10 'Subtract from...' and 'Correction'

### ISSUE THREAD

**Issue by JSmalbu** [UVVIS-BIRA-IASB/qdoas#7]
<img width="638" alt="QDOAS screen capture" src="https://github.com/user-attachments/assets/84ab9d15-676c-4249-82f6-60f74636eb57">
I have a question regarding the use of the 'Subtract from...' and 'Correction' options in Qdoas version 3.6.10. I wasn't able to find detailed information about these features in the downloadable manual. 
Could you kindly clarify if these options are intended to help remove interference from strong absorbers when retrieving weak absorbers? If so, I would greatly appreciate any additional information on how they work and how to properly use them.
Thank you very much for your time and assistance!

**Comment by tdanckaert** [comment]
Hi, for questions about the use of the software, please use the QDOAS section of the ESA Atmospheric Toolbox forum: https://forum.atmospherictoolbox.org/c/qdoas/

thanks!
